### PR TITLE
Remove model matrix from the viewer.

### PR DESCRIPTION
**Pull request by jdumas**
As discussed in #692 and #617, this removes the model matrix from the viewer, which created more confusion than necessary. Also renamed `model_zoom` and `model_translation` to `camera_base_zoom` and `camera_base_translation` respectively (it's best to keep them separate from `camera_zoom` and `camera_translation` to keep the distinction with the user interactions). I also removed `model_zoom_uv` and `model_translation_uv` which were not used anywhere.

I've updated the shaders with the light position accordingly, and the python bindings should be good too.

### CODE REVIEW

**Comment by danielepanozzo** [comment]
Looks good to me. @alecjacobson can you merge if you also approve?

**Comment by jdumas** [comment]
I just have a small doubt. Shouldn't the `normal_eye` in the shader be transformed according to the inverse transpose of the `view` matrix?

Also, it looks like the specular coeff is computed using Phong shading (with the reflected ray from the camera). Shouldn't we use Blinn-Phong instead (with the half-vector instead)?

**Comment by jdumas** [comment]
Also, I was wondering if we should make the trackball/two axis rotation centered around the scene (i.e. apply `camera_zoom` and `camera_translate` after the rotation). Right now when you pan the view and rotate the model, the rotation center is displaced and this is a really not intuitive to me.

**Comment by jdumas** [comment]
Alright I've pushed the change for the normal transformations, and also updated the shaders to normalize `normal_eye` also in the fragment shader (was only normalized in the vertex shader so far, maybe this can be removed).

Now the shading should be correct (you can check on tutorial 201 for reference). Let me know if I should rename the `view` and `proj` matrix in the shader to be consistent with `mat4 normal_matrix;` (`normal` was obviously already taken).

There is also a funny bug in tutorial 201 (which was already present before), if you press <kbd>3</kbd> and then <kbd>2</kbd>, weird stuff happens.

**Comment by danielepanozzo** [comment]
@alecjacobson This is also ready to merge. Can we proceed?

**Comment by jdumas** [comment]
Hi there. This PR has been pending for a while. Just sending a reminder as I'd like to merge this one before #748.

**Pull request merged**
