### PR TITLE
Building a CGAL polyhedron via a float-type Eigen matrix.

### PR DESCRIPTION
**Pull request by metorm**
The origin version only accepts Eigen::MatrixXd as vertices.

Add a template parameter to `igl::copyleft::cgal::mesh_to_polyhedron` so it also accepts `Eigen::MatrixXf` as `V`

- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [ ] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
While you're at it, you might as well add a template parameter to the second argument `F` ...

**Comment by metorm** [comment]
@jdumas What else types can `F` be?

**Comment by jdumas** [comment]
Well signed, unsigned, long, short ... All matrix types in libigl are templated by default, seems like an oversight this one was not.

**Comment by metorm** [comment]
But, in order to support these int types, what shall I do with the STATIC lib? Add 2*4 or even more explicit entries?

**Comment by jdumas** [comment]
No you don't need to create explicit template instantiations for each type, just add the template parameter to the function signature.

**Comment by metorm** [comment]
@jdumas I had updated the PR.

**Pull request merged**
