### PR TITLE
bump embree version; bump sse2 to avx2

### LINKED ISSUE #1632: libigl build fails (embree)
#### Describe your question

I'm getting embree errors (from a fresh copy):

/Users/amirvaxman/libigl/external/embree/kernels/common/rtcore.cpp:1071:7: error: 
      no member named 'createGridMesh' in namespace 'embree::sse41'; did you
      mean simply 'createGridMesh'?
  ...SELECT_SYMBOL_DEFAULT_AVX_AVX2_AVX512KNL_AVX512SKX(device->enabled_cpu_features,createGridMesh);

and

/Users/amirvaxman/libigl/external/embree/kernels/common/rtcore.cpp:1059:7: error: 
      no member named 'createInstance' in namespace 'embree::sse41'; did you
      mean simply 'createInstance'?
  ...SELECT_SYMBOL_DEFAULT_AVX_AVX2_AVX512KNL_AVX512SKX(device->enabled_cpu_features,createInstance);

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [X] macOS
- [ ] Linux

### PR DESCRIPTION
**Pull request by alecjacobson**
Fixes #1632 by updating embree to newest release.

This also bumps the default simd support for embree from SSE2 to AVX2. Embree's cmake will find _all_ that are compatible but then complains that in static mode we can only select one. I'm guessing most folks using this will have avx2 support (let's see).

#### Check all that apply (change to `[x]`)
- [ ] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
@alecjacobson I've rebased onto `master` so the Windows part should build again. Unit tests are now failing on Linux though, something about the ids in the tree not matching after the update.

**Comment by BruegelN** [comment]
Hi @jdumas 
just want to let you know that it works on my old macOS machine (MB Pro from late 2014).
Bildschirmfoto 2020-11-22 um 13 17 21
Let me know if additional testing is useful!

**Comment by jdumas** [comment]
Unfortunately we can't merge until we fix the unit tests, and I haven't had time to dig into why they fail yet...

**Comment by alecjacobson** [comment]
All of the unit tests were degenerate examples of rays hitting edges of the cube mesh. So the embree upgrade picked the _other_ face this time and they all failed. I've pushed a change to make these tests non-degenerate.

**Review by jdumas — APPROVED** [review]

**Pull request merged**
