### PR TITLE
cylinder with caps

### PR DESCRIPTION
**Pull request by wucm1994**
[Describe your changes and what you've already done to test it.]

#### Check all that apply (change to `[x]`)
- [ ] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [ ] This is a minor change.

### CODE REVIEW

**Comment by wucm1994** [comment]
Thanks! Please see if these changes reasonable, really appreciate it!

**Comment by alecjacobson** [comment]
I've reverted this. Please see requested changes.

**Comment by alecjacobson** [comment]
(as a meta comment, @fwilliams , the review process doesn't do much if we immediately merge things after accepting them. Maybe we need to have multiple required reviews or limit write access.)

**Comment by fwilliams** [comment]
I'm sorry about that! I'll be more careful in the future.

Also, what are the requested changes on this PR? I can't see them.

**Comment by fwilliams** [comment]
Maybe let's switch to 2 reviewer approvals to merge something and avoid this problem in the future? The PR looked clean to me and I didn't think the documentation was an issue (that being said, knowing which axis things are aligned to seems like a useful detail now that you point it out :smile: ).

**Comment by alecjacobson** [comment]
I was not upset about the situation, just pointing out that requiring 1 reviewer from somebody who can also write a merge is extra button clicking and email spamming for no reason. As far as I know, we're not allowing anyone to review who can't write merges. So more logical solutions would be: 

 1. limit # people with write access (more conservative merges),
 2. keep current writers but remove superfluous reviewing (less button clicking/spam), or 
 3. require 2 reviews (more people involved in each PR, also more conservative).

**Comment by jdumas** [comment]
This is kinda orthogonal, but email spam can be mitigated by filtering
based on the notification type:
https://help.github.com/articles/about-email-notifications/

This should help isolate explicit @mentions or issues/PR that you get
assigned to. When I review a PR that looks ready to merge I either 1)
approve it and label it “ready-to-merge”, if I think it’s a good to go but
I would like someone else to take a look and hit the merge button, or 2)
approve and merge it directly if it’s a minor thing like a compilation fix
or missing template.

I’m ok with the mail spam personally, but I’m open to trying out changes in
the review process, whatever fits you best.

**Pull request merged**
