### PR TITLE
 Temporary fix for the compiling problem with Xcode 

### PR DESCRIPTION
**Pull request by metorm**
In macOS/ Xcode, libigl failed to build with glfw3 enabled. The root cause of this problem is unknown yet (Maybe something wrong with nano-gui). This patch allows the user to use pre-installed glfw3 in the system to compile, using Xcode 8 or later.

This is mentioned in #383 several months ago and not solved yet.

### CODE REVIEW

**Comment by jdumas** [comment]
Have you tried with a more recent version of NanoGUI? There are two recent PR in NanoGUI that seem related to this issue: [here](https://github.com/wjakob/nanogui/pull/304) and [there](https://github.com/wjakob/nanogui/pull/305). If this works out with a more recent version of NanoGUI, maybe we should instead update the NanoGUI submodule instead of patching things in a hacky way.

**Comment by metorm** [comment]
Not yet. Recently I am too busy to test different build configurations ...

**Comment by svenevs** [comment]
FWIW, updating NanoGUI should fix the XCode problem.  It came from NanoGUI **and** the `GLFW` submodule there (they both have the same problem: a pure object library with no source code makes XCode choke).

As a side note, you can vendor NanoGUI [as GLFW itself](http://nanogui.readthedocs.io/en/latest/compilation.html#nanogui-glfw-and-other-projects).  The key being using `$<TARGET_FILE:nanogui>` and making it a dependency.  I'm not familiar with libigl and what the options are (e.g., allow either NanoGUI or GLFW or both).  If you always build NanoGUI, then use it as GLFW.  This will circumvent the XCode problem, both from NanoGUI and GLFW.

**Comment by jdumas** [comment]
Hi,

I'm closing this PR as I think it does not apply anymore. We now link directly against `glfw` from upstream, which is not defined as an object target. You can still override the version of `glfw` that is used in your project if you define the target before including libigl.

**Pull request closed without merging**
