### PR TITLE
Hunterize libigl

### PR DESCRIPTION
**Pull request by rbsheth**
This PR adds basic support for the Hunter package manager in libigl. Because libigl is already following modern CMake practices, the changes needed to make this package Hunter-ready are minimal.

Changes:
1) Add `HunterGate.cmake` and corresponding CMake code in `CMakeLists.txt`
2) Pull `Eigen` from Hunter
3) Add `HUNTER_ENABLED` flag and default to `OFF` to preserve current behavior.

Once this change is merged, a new (minor?) GitHub release is needed to generate a source tarball that Hunter can pull in.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
Hi. Sorry for the delay. PR looks good, and as this doesn't change default behavior I'm ok with merging it. There are some conflicts with the tip of the `dev` branch though, so if you could solve them and if CI passes I think we can merge it.

@alecjacobson @danielepanozzo I've used Hunter before and it's quite nice. It's a cmake-based package manager. It doesn't cost much to support it for `igl::core` so I don't see any downside to merging this PR. Let me know if you have any comment.

**Comment by danielepanozzo** [comment]
I am also ok with it since it does not change the default behavior.

**Comment by rbsheth** [comment]
Great! @jdumas @danielepanozzo I've updated my branch here: https://github.com/rbsheth/libigl/tree/rbsheth_add_hunter

I think the branch for this PR needs to be re-set to mine (there were some GitHub issues earlier). Here's a comparison of the latest against dev: https://github.com/libigl/libigl/compare/dev...rbsheth:rbsheth_add_hunter?expand=1

**Comment by jdumas** [comment]
Hmm I don't think I can do that in the github interface. Probably better if you close this PR and open a clean one against our current `dev` branch.

**Comment by rbsheth** [comment]
@jdumas Okay, made a new PR here: #1242

**Pull request closed without merging**
