### PR TITLE
Update GLFW to 3.3

### PR DESCRIPTION
**Pull request by jdumas**
Stable version of GLFW 3.3 came out today, so I thought we might update our dependency accordingly.
I've also updated Embree and use git urls instead of direct download due to #1019.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] This is a minor change.

### CODE REVIEW

**Comment by alecjacobson** [comment]
Has this been tested on Mac, Ubuntu and Windows ? (not just CI but actually testing that the tutorial windows appear correctly etc.)

**Comment by jdumas** [comment]
I have tested tutorials 102, 107 and 108 on my Archlinux and they work as expected. I can test on Windows too since we don't have many Windows users, but I don't have a Mac.

**Comment by jdumas** [comment]
Also tested on Windows, and it works fine. I also fixed a cmake issue with top-level project detection (somehow was not working on Windows).

**Comment by BruegelN** [comment]
@jdumas @alecjacobson just wanted to let you know: everything looks fine and behaves as I'd expected it on my MacBook(macOS Mojave 10.14.4)!
I've tested 102, 107 and 108 as well as 106 & 708.

To do so I took the following steps:
```
git clone https://github.com/libigl/libigl.git
cd libigl
git checkout dev
git pull origin update-libs
mkdir build
cd build
cmake ../
make -j4
```

**Pull request merged**
