### PR TITLE
Bump version of glfw.

### PR DESCRIPTION
**Pull request by jdumas**
Current version of glfw produces the following warning with recent versions of CMake:

```
CMake Deprecation Warning at external/glfw/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

The new version has CMake 3.0 as minimum version instead of 2.8.12, but that's ok since our CMake requires 3.1.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] This is a minor change.

### CODE REVIEW

**Comment by fwilliams** [comment]
This is totally orthogonal, but does this fix the transparency issue on Mac that @teseoch was working on?

**Comment by jdumas** [comment]
No this the issue is still open in GLFW (see [here](https://github.com/glfw/glfw/issues/1334) and [there](https://github.com/glfw/glfw/pull/1346). What teseo pushed is a less hacky fix that doesn't involve messing up the transparency or moving the window.

**Comment by jdumas** [comment]
Argh of course it fails to build on Windows =( (but glfw has CI on Windows, so we may be missing something).

**Comment by jdumas** [comment]
Updated again so the compilation bug on Windows is fixed. Anybody on macOS can confirm there's no trouble with the viewer so we can merge? (@teseoch with the multiple dpi?).

**Pull request merged**
