### PR TITLE
Boost+CGAL (dynamic) configuration on Windows fixed

### PR DESCRIPTION
**Pull request by gaoxifeng**

### CODE REVIEW

**Comment by jdumas** [comment]
@gaoxifeng does the boolean tutorial compile for you on Windows with `LIBIGL_USE_STATIC_LIBRARY ON`? (Make sure to clear your cache/rebuild). I managed to install Boost on my laptop (yay), and I get a lot of undefined references (missing explicit template instantiations).

**Comment by danielepanozzo** [comment]
@jdumas do you think it is possible to have the cgal tutorials enabled in appveyor? Did you manage to install boost + cgal with a script on your laptop?

**Comment by jdumas** [comment]
We could try to build CGAL from the github repository. And it should be possible to build boost from a script in appveyor.

**Comment by jdumas** [comment]
I've added the missing template instantiation for CGAL on Windows + a convenience function to copy CGAL's dlls on Windows (the function does nothing on Mac/Linux).

**Pull request merged**
