### PR TITLE
solve fragmentation issue with remesh_along_isoline (cleaned up)

### PR DESCRIPTION
**Pull request by BruegelN**
Cleaned up version of https://github.com/libigl/libigl/pull/1175 by cherry-picking only the related changes.
I hope you, @n-taka, are fine with this, if not please let me know. In the end, of course, it's still your contribution.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] Adds new .cpp file.
- [x] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by BruegelN** [comment]
Despite Travis CI is failing due to `ccache` it works on my macbook.

**Comment by jdumas** [comment]
Did you merge the branch with the tip of the libigl `dev` branch? This issue appears on the master branch, but was fixed in the dev branch.

**Comment by BruegelN** [comment]
I'm aware of the issue with Travis CI and the `master` banch. However I cherry-picked and rebased on top of the current `dev` so I don't know what's the root cause?!
Somehow Travis CI changed the way to install `ccache` on macOS: https://docs.travis-ci.com/user/caching/#ccache-on-macos
You need to install `brew install ccache` manually.
See also: https://github.com/libigl/libigl/pull/1422#issuecomment-591101696
But as @jdumas already mentioned maybe wait until GitHub Actions are used.

**Comment by BruegelN** [comment]
Rebased on latest `dev` and with the usage of Github Actions the ccache issue is resolved (as expected).
BTW: Rebased my other PR on latest `dev`, too. Github Actions seem to work quite nice and quick, thanks @jdumas!

**Comment by jdumas** [comment]
Actually we're gonna remove 'dev' in the future, new PR should be based on 'master' (and we'll use 'stable' to point to the latest tagged release)

**Review by alecjacobson — APPROVED** [review]

**Pull request merged**
