### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Most are non-user facing. Hope this is not too annoying of a PR. 

Used `codespell -d -q 3 --skip="*.po,*.ts,./.git,./external"` to locate relevant typos.

### CODE REVIEW

**Comment by danielepanozzo** [comment]
Looks good to me. Let's wait for an approval from @alecjacobson

**Comment by luzpaz** [comment]
@alecjacobson care to weigh in ?

**Comment by luzpaz** [comment]
I can squash the commits together when the time comes. Please review 2nd commit. Thanks!

**Comment by luzpaz** [comment]
darn, messed up the rebase. let me see if i can fix

**Comment by luzpaz** [comment]
please review

**Comment by danielepanozzo** [comment]
Looks good to me. @alecjacobson shall we merge?

**Pull request merged**
