### PR TITLE
Add functionality to retain markers from triangle and tetgen

### PR DESCRIPTION
**Pull request by nclement**
I've exposed the functionality from tetgen and triangle to retain the markers for original verts (from verts and edges for triangle and verts and faces from tetgen). I've verified it's functionality on my own system.

### CODE REVIEW

**Comment by alecjacobson** [comment]
nice. Let me take a look.

**Comment by nclement** [comment]
Hey I just noticed I've got a bunch of printfs in both .cpp files that were there just for debug purposes. These should be removed before the branch is merged--I can either fix that and create a new pull request or you can just remove them.

**Comment by alecjacobson** [comment]
I think you can add commits to this pull request.

**Comment by danielepanozzo** [comment]
Any news on this request? @alecjacobson: is it good to be merged or do you still want to take a look?

**Comment by alecjacobson** [comment]
I want to double check that examples using these still work (not just
compile). Testing the dependent tutorials shoul be enough.

**Comment by danielepanozzo** [comment]
Thank you for the pull request!

**Pull request merged**
