### PR TITLE
yet another openmp parallel

### PR DESCRIPTION
**Pull request by xianyuMeng**
Hi, I'm learning libigl and here is my minor change to it:
Rewrite the include/parallel_for.h file. The function args remains the same but use openmp for multi-thread parallel.
In the code I use std::forward and universal reference&& to help us do it.
I wrapped it with another namespace so it will not conflict with the original one.

#### Check all that apply (change to `[x]`)
- [ ] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by alecjacobson** [comment]
openmp is not supported with the builtin clang on Mac OS X so we can't have it as a dependency. The current parallel_for only depends on C++11 threads. It has some known flaws: it spawns new threads rather than using a pool, it will spawn too many threads if called recursively, etc.

For internal use, this is mostly OK. If an external project is OK with openmp, they can probably just use `#pragma omp parallel for` directly.

We've previously discussed adding TBB as a dependency to do fancier multi-threading, but currently that's not a priority / benefit doesn't seem to outweigh cost.

Since OMP can be hidden through preprocessor macros, it'd be interesting to see if this could be merged seamlessly into the existing `parallel_for` so that it uses openmp if available and `std::thread` otherwise. But to me that sounds like reimplementing a poor man's tbb...

**Comment by jdumas** [comment]
Do you have any benchmark for that? That'd be interesting to have some measurement available (of course, performances will highly depend on the problem being treated...).

I have a version of my own ParallelFor with C++11 threads that uses a naive thread pool and an atomic counter (much better than mutex on Windows) pull jobs from the for loop. Might be worth comparing it at some point with the current implementation:

```cpp
#pragma once

////////////////////////////////////////////////////////////////////////////////
#include <atomic>
#include <thread>
#include <vector>
#include <cmath>
////////////////////////////////////////////////////////////////////////////////

class ThreadPool {

public:

	// Launch a for loop in parallel using a simple thread pool
	template<typename Index, typename Callable>
	static void ParallelFor(Index start, Index end, Callable func) {
		// Estimate number of threads in the pool
		const static unsigned nb_threads_hint = std::thread::hardware_concurrency();
		const static unsigned nb_threads = (nb_threads_hint == 0u ? 8u : nb_threads_hint);

		// Atomic counter for the parallel loop
		std::atomic<Index> idx(start);

		// [Helper] Increment atomic counter and launch job
		auto launchFunc = [&idx, &start, &end, &func] () {
			for (Index k = idx++; k < end; k = idx++) {
				func(k);
			}
		};

		// Create pool and launch jobs
		std::vector<std::thread> pool;
		pool.reserve(nb_threads);
		for (unsigned i = 0; i < nb_threads; ++i) {
			pool.emplace_back(launchFunc);
		}

		// Wait for jobs to finish
		for (std::thread &t : pool) {
			if (t.joinable()) {
				t.join();
			}
		}
	}

	// Split a sequential for loop into N multiple parallel loops
	template<typename Index, typename Callable>
	static void ParallelForRange(Index start, Index end, Callable funcRange) {
		// Estimate number of threads in the pool
		const static unsigned nb_threads_hint = std::thread::hardware_concurrency();
		const static unsigned nb_threads = (nb_threads_hint == 0u ? 8u : nb_threads_hint);

		// Size of a slice for the range functions
		Index n = end - start + 1;
		Index slice = (Index) std::round(n / static_cast<double> (nb_threads));
		slice = std::max(slice, Index(1));

		// Create pool and launch jobs
		std::vector<std::thread> pool;
		pool.reserve(nb_threads);
		Index i1 = start;
		Index i2 = std::min(start + slice, end);
		for (unsigned i = 0; i + 1 < nb_threads && i1 < end; ++i) {
			pool.emplace_back(funcRange, i1, i2);
			i1 = i2;
			i2 = std::min(i2 + slice, end);
		}
		if (i1 < end) {
			pool.emplace_back(funcRange, i1, end);
		}

		// Wait for jobs to finish
		for (std::thread &t : pool) {
			if (t.joinable()) {
				t.join();
			}
		}
	}

	// Serial version for easy comparison
	template<typename Index, typename Callable>
	static void SequentialFor(Index start, Index end, Callable func) {
		for (Index i = start; i < end; i++) {
			func(i);
		}
	}

	// Serial version for easy comparison
	template<typename Index, typename Callable>
	static void SequentialForRange(Index start, Index end, Callable funcRange) {
		funcRange(start, end);
	}

};
```

**Comment by ikoruk** [comment]
Here were our benchmarks, each "BenchX" is a certain problem averaged over 5 runs (I unfortunately cannot share the actual problems we were benchmarking):

All time in seconds, lower is better.

_Linux_:

Problem | C++11 Threads | OpenMP | TBB
-- | -- | -- | --
Bench1 | 15.7415078 | 19.937248 | 20.862913 | 18.765513
Bench2 | 6.4938446 | 6.961244 | 7.751636 | 6.382878
Bench3 | 19.891599 | 19.893276 | 19.499946
Bench4 | 6.516180 | 6.345036 | 7.122722

_Mac_:

Problem | C++11 Threads | OpenMP | TBB
-- | -- | -- | --
Bench1 | 21.706410 | 23.919128 | 21.853211
Bench2 | 7.029042 | 6.822062 | 6.699846

FWIW, I tried a simple test with increasing numbers of threads on a 24 thread Mac OS machine:

```
CXX11_THREADS
time = 5.05942 with 1 threads
time = 3.00603 with 2 threads
time = 2.34695 with 3 threads
time = 2.03337 with 4 threads
time = 1.80214 with 5 threads
time = 1.69077 with 6 threads
time = 1.56187 with 7 threads
time = 1.49186 with 8 threads
time = 1.42286 with 9 threads
time = 1.38841 with 10 threads
time = 1.35974 with 11 threads
time = 1.34687 with 12 threads
time = 1.33626 with 13 threads
time = 1.31 with 14 threads
time = 1.29602 with 15 threads
time = 1.26882 with 16 threads
time = 1.24469 with 17 threads
time = 1.2215 with 18 threads
time = 1.21292 with 19 threads
time = 1.19188 with 20 threads
time = 1.16673 with 21 threads
time = 1.15207 with 22 threads
time = 1.13923 with 23 threads
time = 1.12755 with 24 threads

TBB
time = 6.62909 with 1 threads
time = 4.07634 with 2 threads
time = 3.09675 with 3 threads
time = 2.6521 with 4 threads
time = 2.38919 with 5 threads
time = 2.23614 with 6 threads
time = 2.09614 with 7 threads
time = 2.00754 with 8 threads
time = 1.94593 with 9 threads
time = 1.8967 with 10 threads
time = 1.86831 with 11 threads
time = 1.85433 with 12 threads
time = 1.83325 with 13 threads
time = 1.77768 with 14 threads
time = 1.74081 with 15 threads
time = 1.69866 with 16 threads
time = 1.66532 with 17 threads
time = 1.64561 with 18 threads
time = 1.61842 with 19 threads
time = 1.59114 with 20 threads
time = 1.59103 with 21 threads
time = 1.55431 with 22 threads
time = 1.56262 with 23 threads
time = 1.54748 with 24 threads

OPENMP
time = 7.33652 with 1 threads
time = 4.52531 with 2 threads
time = 3.60955 with 3 threads
time = 3.09784 with 4 threads
time = 2.69174 with 5 threads
time = 2.4604 with 6 threads
time = 2.30304 with 7 threads
time = 2.16734 with 8 threads
time = 2.11621 with 9 threads
time = 2.03354 with 10 threads
time = 2.01456 with 11 threads
time = 1.97624 with 12 threads
time = 1.92764 with 13 threads
time = 1.88972 with 14 threads
time = 1.86804 with 15 threads
time = 1.83383 with 16 threads
time = 1.83807 with 17 threads
time = 1.80358 with 18 threads
time = 1.75967 with 19 threads
time = 1.76041 with 20 threads
time = 1.7324 with 21 threads
time = 1.70316 with 22 threads
time = 1.70158 with 23 threads
time = 1.70032 with 24 threads
```

**Comment by ikoruk** [comment]
We didn't touch it much but, as far as I recall, the tests were made such that N was quite big and each thread did finish fast.

**Pull request closed without merging**
