### PR TITLE
dont use floating point values to index eigen types

### PR DESCRIPTION
**Pull request by Janos95**
As discussed in the corresponding issue, I changed the necessary files so there are no Eigen array accesses using floating point types.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
@Janos95 can you rename `cut_mesh_rosy.cpp` back to `cut_mesh.cpp`?

**Comment by Janos95** [comment]
Sorry, I thought this was already merged so I pushed some other work onto my fork.

**Comment by jdumas** [comment]
Thanks! But I think my comment from last time still applies (about casting only the doubles, not the whole expr). I would have merged it earlier but our current CI is a bit wonky (it often times out and I need to restart it manually).

**Comment by Janos95** [comment]
I think I corrected that in 5b996d9 .

**Comment by jdumas** [comment]
5b996d9 only changed one line, but I think the comment applies to other lines as far as I can tell from the PR summary.

**Pull request merged**
