### PR TITLE
Winding number propagation

### PR DESCRIPTION
**Pull request by qnzhou**
Pull request summary:

* Bug fix in order facets around edge.
* Bug fix in resolving intersection due to CDT ambiguities.
* Add function to extract manifold patches from mesh.
* Add function to extract cells partitioned by the input mesh.
* Add function to extract non-manifold edge curves from input mesh.
* Add function propagate winding number from infinity into the cells.
* Add function to peel winding number layers.
* Update boolean operations to be based on winding number.

### CODE REVIEW

**Comment by alecjacobson** [comment]
What's the difference between `extract_manifold_patches` and the existing `orientable_patches`?

**Comment by qnzhou** [comment]
I guess there is no difference besides the interface.  We could keep just
one of them.

**Comment by alecjacobson** [comment]
If the mesh is a moebius strip what will extract_manifold_patches do?

**Comment by qnzhou** [comment]
It would extract just a single patch.

**Comment by alecjacobson** [comment]
I think orientable_patches will do the same. I'll make a "to do" to merge these. For now I'm still plugging away at getting this pull request to compile...

**Comment by qnzhou** [comment]
Ahhh sorry :(  I thought I have it compiling.  Is it the tutorial that
failed to compile?

**Comment by alecjacobson** [comment]
Yes, the version with the static library. I'll fix it this time and I'm creating instructions for future pull requests.

**Comment by alecjacobson** [comment]
I've started combing out these implementations a bit. Some documentation is still missing and there are many "style" issues (see https://github.com/libigl/libigl/blob/master/style-guidelines.md): floating helper functions, classes and naming conventions, etc.

**Comment by qnzhou** [comment]
ok, I can go through the files and clean up the style issues.

If encapsulation in a separate file is not possible or does not make sense,
> then avoid crowding the namespace by creating lambda functions within the
> function implmentation.


So the usage of lambda functions within a function is also discouraged?

**Comment by alecjacobson** [comment]
Thanks.

No, that means that we'd rather have lambdas than floating single-use
helper functions. Though, neither are great.

**Pull request merged**
