### PR TITLE
Replace .ply reader/writer with tinyply library

### PR DESCRIPTION
**Pull request by vfonov**
Using tinyply library for reading and writing .ply files:

based on libigl/libigl#1235, allows reading and writing additional per-vertex, per-face and per-edge properties, using tinyply version 2.3.2. 

[Describe your changes and what you've already done to test it.]

#### Check all that apply (change to `[x]`)
- [ ] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] Adds new .cpp file.
- [x] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [ ] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
Thanks! Did you also update the `libigl-test-repo` and point this PR to the update SHA1 so it can be tested on Travis before we merge it?

**Comment by vfonov** [comment]
ok, I forgot about that

**Comment by jdumas** [comment]
Thanks. How about `mesh_error.ply` though, do you have it?

**Comment by vfonov** [comment]
it's supposed to be missing : https://github.com/vfonov/libigl/blob/tinyply_reader_writer/tests/include/igl/readPLY.cpp#L69

**Comment by jdumas** [comment]
Ahah my bad. I'll take a look at the PR this weekend then, hopefully we can merge it.

**Comment by vfonov** [comment]
I made more changes and also updated SHA for test data.

**Comment by vfonov** [comment]
I have trouble replicating these bugs on my system (either Ubuntu 18.04 or MacOS)

**Comment by jdumas** [comment]
Hmm seems like it's still not building on Travis/AppVeyor...

**Comment by vfonov** [comment]
ok, I think I got why there were errors with template instantiation

**Comment by vfonov** [comment]
another attempt...

**Comment by vfonov** [comment]
At least it builds with gcc-7, looks like something is wrong with the build setup for macosX though

**Comment by vfonov** [comment]
it's not quite clear why it fails now on appveyor

**Comment by jdumas** [comment]
Yeah the timeout issue on AppVeyor is a known issue. For the build on macOS you should rebase your changes onto our `dev` branch, which contains fixes to the .travis.yml for macOS.

**Comment by vfonov** [comment]
looks like rebasing didn't help

**Comment by vfonov** [comment]
maybe you need to add command to explicitly install ccache, as per https://docs.travis-ci.com/user/caching/#ccache-on-macos ?

**Comment by jdumas** [comment]
No ccache should be available thanks to [this line](https://github.com/libigl/libigl/blob/26053f696cd2ec01f819ff353392e4201742fc97/.travis.yml#L22). But honestly I'm not super inclined to debug build issues on Travis, since I'm waiting on #1389 to get merged and we switch to GitHub Actions for CI builds. Most likely I suspect this is not gonna happen till March 20 where we'll have our next libigl hackaton planned.

**Comment by vfonov** [comment]
so, installing ccache with `brew install ccache` seem to have worked - the only thing crashing now is CGAL on windows, but I think it's not related.

**Comment by alecjacobson** [comment]
The current ply reader appears to fail on bun_zipper.ply (only loads two coordinates instead of all three). Could you try this model with this PR and see if it loads correctly? (then I don't have to debug the old reader). http://graphics.stanford.edu/pub/3Dscanrep/bunny.tar.gz

**Comment by vfonov** [comment]
Seem to work: showing bunny/reconstruction/bun_zipper.ply with "confidence" property as per-vertex data
image

**Comment by alecjacobson** [comment]
the current readPLY seems to fail consistently on these plys https://gfx.cs.princeton.edu/proj/sugcon/models/

Does this PR succeed on those?

**Comment by vfonov** [comment]
I made a small test program  : check_ply.cpp [check_ply.cpp.txt](https://github.com/libigl/libigl/files/4330253/check_ply.cpp.txt) and tested it on the PLY files from the location. Here is the output. It looks like all these models are using "tristrips" property instead of "faces" , so loader doesn't load faces matrix (it's 0x0):
`
PLY:armadillo.ply Success:	V: 172974x3	F: 0x0	D: 0x0	
PLY:brain2.ply Success:	V: 294012x3	F: 0x0	D: 0x0	
PLY:brain.ply Success:	V: 18844x3	F: 0x0	D: 0x0	
PLY:bunny2.ply Success:	V: 72027x3	F: 0x0	D: 0x0	
PLY:bunny.ply Success:	V: 34834x3	F: 0x0	D: 0x0	
PLY:cow2.ply Success:	V: 46433x3	F: 0x0	D: 0x0	
PLY:cow.ply Success:	V: 2903x3	F: 0x0	D: 0x0	
PLY:elephant2.ply Success:	V: 78792x3	F: 0x0	D: 0x0	
PLY:elephant.ply Success:	V: 19753x3	F: 0x0	D: 0x0	
PLY:golfball.ply Success:	V: 122882x3	F: 0x0	D: 0x0	
PLY:heptoroid.ply Success:	V: 286678x3	F: 0x0	D: 0x0	
PLY:hippo.ply Success:	V: 23105x3	F: 0x0	D: 0x0	
PLY:horse2.ply Success:	V: 48484x3	F: 0x0	D: 0x0	
PLY:horse.ply Success:	V: 48484x3	F: 0x0	D: 0x0	
PLY:igea.ply Success:	V: 134345x3	F: 0x0	D: 0x0	
PLY:lion2.ply Success:	V: 183408x3	F: 0x0	D: 183408x3	diffuse_red,diffuse_green,diffuse_blue,
PLY:lion.ply Success:	V: 183408x3	F: 0x0	D: 183408x3	diffuse_red,diffuse_green,diffuse_blue,
PLY:lucy.ply Success:	V: 262909x3	F: 0x0	D: 0x0	
PLY:maxplanck.ply Success:	V: 49132x3	F: 0x0	D: 0x0	
PLY:pear.ply Success:	V: 10759x3	F: 0x0	D: 0x0	
PLY:santa2.ply Success:	V: 75781x3	F: 0x0	D: 75781x3	diffuse_red,diffuse_green,diffuse_blue,
PLY:santa.ply Success:	V: 75781x3	F: 0x0	D: 75781x3	diffuse_red,diffuse_green,diffuse_blue,
PLY:torus.ply Success:	V: 4800x3	F: 0x0	D: 0x0	



`

**Comment by vfonov** [comment]
ok, I managed to treat this case, will push another commit soon

**Comment by vfonov** [comment]
The latest version can read ply files with tristrips instead of faces. 
I modified my check script, and run on all the ply files from the princeton library.
[check_ply.cpp.txt](https://github.com/libigl/libigl/files/4331070/check_ply.cpp.txt)
armadillo ply
brain ply
brain2 ply
bunny ply
bunny2 ply
cow ply
cow2 ply
elephant ply
elephant2 ply
golfball ply
heptoroid ply
hippo ply
horse ply
horse2 ply
igea ply
lion ply
lion2 ply
lucy ply
maxplanck ply
pear ply
santa ply
santa2 ply
torus ply

**Comment by vfonov** [comment]
So, is there some concerns about including these changes into the dev branch?

**Comment by jdumas** [comment]
@alecjacobson is probably busy with the SIGGRAPH committee until the end of the week. Once he gives the green light we can merge this.

**Pull request merged**
