### PR TITLE
ShapeUp projection method

### PR DESCRIPTION
**Pull request by avaxman**
With tutorial and demo updated.

### CODE REVIEW

**Comment by alecjacobson** [comment]
This looks really cool. Could you please add "Input" / "Output" comments in the headers above each exposed function? See `cotmatrix.h` for an example.

**Comment by avaxman** [comment]
You mean the projection functions? becuase there are such comments in the
shapeup core functions, no?

**Comment by alecjacobson** [comment]
Yeah, I think those are the only ones missing (I just clicked on the first header I saw).

**Comment by avaxman** [comment]
Right. Do I just do that and create another pull request?

**Comment by avaxman** [comment]
hmmm pull requests update automatically, so there it is :-)

**Pull request merged**
