### PR TITLE
Keep reference to multiple material when reading obj

### PR DESCRIPTION
**Pull request by DerouineauNicolas**
This PR adress issue #1276. It goes along with PR 2 on libigl-testdata.

I choose a tuple list to store (faces vertices index, ..., material). I'm not sure it's a right choice and I'll be happy to have a second opinion.

I did a function overload for readOBJ. This leads to code duplication (which is always bad).

### CODE REVIEW

**Comment by jdumas** [comment]
So this code is node reading the material file at all? Apart from that, I would suggest returning the list of face-material associations as a vector or ranges into face indices. So a `vector<tuple<string, int, int>>` maybe? Where each a entry `(material_name, f0, f1)`  means faces `f0 <= f < f1` are using `material_name`.

To avoid code duplication, you could also consider having each function use the mode generic overload (that reads material associations) and drops the material info if not needed.

**Comment by DerouineauNicolas** [comment]
Thanks for the suggestion, your solution for the face/materail association is indeed simpler.

I don't understand your suggestion to avoid code duplication. Could you point me to an example about generic function overload in C++ ?

**Comment by jdumas** [comment]
Just look at [this one](https://github.com/libigl/libigl/blob/b0d7740e0b7e887a7e93601c4c557ecf762b389b/include/igl/readPLY.cpp#L207) for example. Use an overloaded function and create temporary arguments to pass to the *more generic* version of the function (the one with the most arguments).

**Comment by DerouineauNicolas** [comment]
@jdumas Should be ok now for the vector<tuple<string, int, int>>

**Comment by jdumas** [comment]
Looks like the CI didn't pass, probably you need to update the SHA1 commit for the test data repository?

**Comment by DerouineauNicolas** [comment]
Hum ... I think I didn't catch how to update the SHA1 for the test data repository.

**Comment by jdumas** [comment]
It's [here](https://github.com/libigl/libigl/blob/c645aac0c5852fad6fabe8c192fdc8675e607263/cmake/LibiglDownloadExternal.cmake#L178).

**Comment by DerouineauNicolas** [comment]
Correct me if I'm wrong, but I guess the PR on the test data repo needs to be merged first.

**Comment by jdumas** [comment]
You need to create a PR on the `libigl-test-data` repo, so that your SHA1 becomes known to github under this URL. Maybe you need to change also the URL in the CMake to point to your fork (for the purpose of this PR). Once this passes the CI, we can merge both the PR in the test data repo, and update this one to point to the new tip in libigl-test-data's master.

**Comment by jdumas** [comment]
So you may need to also update the URL in the CMake to point to your own fork. Once this passes the CI, we can merge the PR in the test-data repo, and update this one to point to the new tip of the test-data master branch.

**Pull request merged**
