### PR TITLE
Matplotlib colormaps

### PR DESCRIPTION
**Pull request by josefgraus**
Added new perceptually uniform colormaps created for matplotlib: https://bids.github.io/colormap/

Magma, Inferno, Plasma, and Viridis are included in this PR.

### CODE REVIEW

**Comment by danielepanozzo** [comment]
Thank you for the contribution! It seems that all files are similar, with the exception of that static array at the top of the .h. If this is the case, I suggest to merge them into a single function (that could also contain the current jet.h), that takes the type of colormap as an additional parameter. @alecjacobson : what do you think?

**Comment by alecjacobson** [comment]
We should definitely factor out the duplicate code across all these files and `jet`,`parula`. 

I'd also recommend taking a look at http://colorbrewer2.org/ Unlike the historical colormaps in matlab/matplotlib these are the result of studying how people perceive colors and data.

**Comment by josefgraus** [comment]
That was the original plan, but I was concerned about breaking jet in older code. I can migrate everything over to some "colormap" header, and pull in jet/parula. To keep it one function per include, there would be a simple enum to switch between colormaps. For compatibility sake, we can flag jet and parula as deprecated code via attributes ( http://en.cppreference.com/w/cpp/language/attributes ) until such time as it's appropriate to remove the older implementations.

**Comment by alecjacobson** [comment]
Sounds good to me. Just have `jet` and `parula` internally call your new
function with the relevant enum value.

**Comment by josefgraus** [comment]
That took an unnecessarily large number of passes to get that through the checks.. I suppose I should set up a static build environment for future work to avoid the headache, ha.

**Comment by josefgraus** [comment]
Inferno
inferno

Jet
jet

Magma
magma

Parula
parula

Plasma
plasma

Viridis
viridis

**Comment by danielepanozzo** [comment]
Looks great, than you for the contribution.

**Comment by alecjacobson** [comment]
I am cleaning up these files to meet the libigl style guidelines. Ideally we should do this _before_ merging PRs.

**Pull request merged**
