### PR TITLE
Issue 521

### PR DESCRIPTION
**Pull request by allo-**
Provide a unit test and a fix for #521

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] Adds new .cpp file.
- [x] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
It seems this PR also include changes from bc0b28b and 2e05d55. Can you rebase onto `dev` an force-push to show only your changes?

**Comment by allo-** [comment]
Can I do anything to get this merged?

**Comment by jdumas** [comment]
Hi,

I was waiting for @qnzhou to review the code before I can merge it. Try to ping again after the SIGGRAPH deadline (Jan 24). Apologies for the delay.

**Comment by allo-** [comment]
Ok. Good luck for your submissions.

**Comment by allo-** [comment]
Ping @jdumas @qnzhou.
I changed the indention in the mean time and the tests still run fine.
It would be nice, when you have time to review and merge it.

**Pull request merged**
