### PR TITLE
Extended mesh operations

### PR DESCRIPTION
**Pull request by schuellc**
* Add cut mesh along edges function cut_mesh_simple
  (Supposed to replace current cut_mesh function at some
  point)
* Extended and fixed HalfEdgeIterator  (renamed some
  functions for consistency)
* Fix various spellings in comments

### CODE REVIEW

**Comment by alecjacobson** [comment]
Thanks. I don't understand the naming convention though. Why are some  `cut_mesh` functions in `cut_mesh_simple.h` ? What's stopping us from replacing the current `cut_mesh` with these now?

**Comment by schuellc** [comment]
I know, for now its just a temporary hack. Since cut_mesh is heavily used in other parts of libigl i didn't want to changes this on my own. I think Olga Diamanti should have a look at it before or Daniele.

**Comment by alecjacobson** [comment]
Ok. In that case let's keep temporary hacks out of the master branch.

**Comment by schuellc** [comment]
So, do you prefer this to be resolved in my fork first?
Or is there gonna be an official dev branch to work on together?

**Comment by alecjacobson** [comment]
I'll create a temporary branch for the viewer refactor and then we could merge this PR there. and then eventually merge it into the master. Does that sound OK?

**Comment by danielepanozzo** [comment]
Sounds good, I will be happy to take care of moving the viewer in the glfw folder and move the nanogui dependency as a plugin after the new branch will pass the tests. 

@schuellc: Regarding cut_mesh, it is used mainly for MIQ. If your new code works in tutorial 505 and the tutorial produces the same output as before, then let's go ahead and replace the old version.

**Comment by schuellc** [comment]
Ok, that sound good. I will take care of replacing the old cut_mesh function.

**Comment by alecjacobson** [comment]
I've picked out the typo corrections from this, but am closing the rest for now. If any important changes in this remain, please submit them individually.

**Comment by jiangzhongshi** [comment]
Hi,

What's the current progress of `cut_mesh_simple`?
It can be a useful function, and since the signature doesn't conflict, maybe it can be provided as an overload, and deprecate the original `cut_mesh`  gradually.

**Pull request closed without merging**
