### PR TITLE
fix: segments_intersect bug.

### PR DESCRIPTION
**Pull request by xarthurx**
also test if t is larger than 1.

[Describe your changes and what you've already done to test it.]

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
@xarthurx We've now moved to using Catch2 on the `dev` branch. Do you want to give it a try to writing a unit test for the two cases described in #957 and #965 ? (Should be easy to match other existing tests in the folder.)

**Comment by xarthurx** [comment]
@jdumas  Yes. Will do soon. Thank you.

**Comment by jdumas** [comment]
This looks like a [missing template instantiation](https://libigl.github.io/before-submitting-pull-request/#troubleshooting).

**Comment by xarthurx** [comment]
@jdumas Inside the test file? Why other test file doesn't have this?

Like this:
image

?

**Comment by xarthurx** [comment]
@jdumas 
OK, I think I know why the error happens now.
The original libigl use RowVector3d as a template, instead of Vector3d.
I changed the test file to use RowVector3d and now it works.

**Comment by jdumas** [comment]
No the template instantiation should be added at the end of `segment_segment_intersect.cpp`.

PS: Why did you open another pull-request for the test? Can you close one of them?

**Comment by xarthurx** [comment]
the last one was on master branch, this is on dev branch. yes, will do.

**Comment by xarthurx** [comment]
close this PR since there's a new one on the dev branch with unit test.

**Pull request closed without merging**
