### PR TITLE
Allow empty input in exact_geodesic

### PR DESCRIPTION
**Pull request by jiangzhongshi**

### CODE REVIEW

**Comment by jiangzhongshi** [comment]
It was based on the failed Travis and reopen is easier than a merge.

**Comment by jdumas** [comment]
Can't you trigger a rebuild on on Travis directly? It will use the latest tip of the master automatically. If you can't trigger the build yourself then just ask us to do so :p

**Comment by jiangzhongshi** [comment]
But the Travis config changed...

**Comment by jdumas** [comment]
Yes but if you re-trigger the build, it will use the result of merge from the master's latest tip and your PR branch, aka Travis will build using the updated master's script. I had a couple of PRs like that which I opened before you fixed the Travis script, and now they pass the build. Again it's not a big deal, bug it's best not to clutter the repo with duplicated PRs if possible.

**Comment by jiangzhongshi** [comment]
Ok, I didn’t know that. Noted :)

**Pull request closed without merging**
