### PR TITLE
explicit instantiation of boundary_loop for std::vector<std::vector<int>>

### PR DESCRIPTION
**Pull request by ShuangLiu1992**
…nt>>

explicit instantiation of boundary_loop for std::vector<std::vector<int>>

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [ ] Adds corresponding python binding.
- [x] This is a minor change.

### CODE REVIEW

**Comment by jdumas** [comment]
There are some conflicts with the file under the `dev` branch. Can you resolve them before we can merge?

**Comment by ShuangLiu1992** [comment]
Sorry I made the PR from master, does merging branch 'dev' into master this work?
should I maybe make a PR from dev instead?

**Comment by jdumas** [comment]
You can `git merge origin/dev` on your branch and reopen this PR.

**Comment by ShuangLiu1992** [comment]
I think I did that but it doesn't pass the CI checks anymore
here is another PR made on the dev branch:
https://github.com/libigl/libigl/pull/1093

**Comment by jdumas** [comment]
Ok, you need to stop creating a new PR every time you want to fix something. Please push new commits onto your branch until it passes the tests.

**Comment by ShuangLiu1992** [comment]
so I have push the new commits to https://github.com/libigl/libigl/pull/1093
The fork this PR is based on has been deleted so I can't make the changes here

**Comment by jdumas** [comment]
Yes, what I'm saying is please to create more forks and PRs =)

**Comment by ShuangLiu1992** [comment]
apologies for making a mess

**Pull request closed without merging**
