### PR TITLE
fix use of protected constructor

### PR DESCRIPTION
**Pull request by Luk0r**
use of protected constructor changed

### CODE REVIEW

**Comment by Luk0r** [comment]
partly fixing:
https://github.com/libigl/libigl/issues/595

**Comment by Luk0r** [comment]
should be the same fix as in:
https://github.com/libigl/libigl/pull/594

**Comment by luca-penasa** [comment]
I am hitting this same bug (for AABB.cpp)... Is there some reason why this pull cannot be accepted?

btw travis-ci seems to exit correctly from the build although here is reported that the build failed (?)

**Comment by danielepanozzo** [comment]
@alecjacobson I think this could be merged, the reported travis failure seems to be just a bug in travis, the build runs successfully.

**Comment by jdumas** [comment]
This has been merged in #659.

**Pull request closed without merging**
