### PR TITLE
Updated submodules, added tutorial 404

### PR DESCRIPTION
**Pull request by s-koch**

### CODE REVIEW

**Comment by s-koch** [comment]
The new version of GLFW does not export the GL library, switched back to manual inclusion.

**Comment by s-koch** [comment]
@danielepanozzo Could you already check if you can replicate the problem with another version of clang?

**Comment by alecjacobson** [comment]
Is this pull request obsolete now? (doing some house cleaning)

**Comment by s-koch** [comment]
No, it should still be pulled to the main repo.

**Comment by danielepanozzo** [comment]
Sorry I totally forgot about this. Tested and merged.

**Pull request merged**
