### PR TITLE
add , 0 to index into area which supports different version of Eigen

### PR DESCRIPTION
**Pull request by fwilliams**
The local version of Eigen I am using does not support indexing Nx1 Matrices as `M(idx)` and requires `M(idx, 0)`. The fast winding number code breaks because of this. This PR adds changes `A(idx)` to `A(idx, 0)` in fast_winding_numbers.cpp. 

This shouldn't require any new tests and should be mergeable assuming unit tests pass.

#### Checklist

- [ ] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [ ] Adds new .cpp file.
- [ ] Adds corresponding unit test.
- [x] This is a minor change.

### CODE REVIEW

**Comment by alecjacobson** [comment]
Is that a new version of Eigen?

I don't know if it's important here, but one reason to use `M(idx)` instead of `M(idx,0)` is that `M(idx)` will work for both Nx1 and 1xN. A lot of times our templates are generous enough to accept both.

**Comment by fwilliams** [comment]
It fails on both Eigen 3.4 and 3.3.7

**Comment by alecjacobson** [comment]
oh no. aren't we using 3.4.0? Is this not being caught be CI?

**Comment by alecjacobson** [comment]
Could you post a little example with your compilation error?

**Comment by alecjacobson** [comment]
I think I hit something similar using numpyeigen and I wonder if it's related to your issue. https://github.com/fwilliams/numpyeigen/blob/96c6356102a9f6c6eca5dd5446c4513552c12da9/src/npe.h defines maps only on Matrix types (e.g., `Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>`) but some libigl functions are expecting that an input argument is a `Eigen::*Vector*` type (i.e., at _compile time_ one of the dimensions is `1`).

**Comment by alecjacobson** [comment]
And if so, then it seems an easy fix is if your input is `X` then call the function with `X.reshaped()`

**Comment by alecjacobson** [comment]
I'm closing this for now. I think the correct solution is to change NPE to support compile-time "vector" types and pass them as expected to libigl. This way libigl continues to work with both "row vectors" and "column vectors".

**Pull request closed without merging**
